import { nanoid } from 'nanoid';

// HEAD DATA
export const headData = {
  title: 'Sultan | Wev Developer', // e.g: 'Name | Developer'
  lang: 'en', // e.g: en, es, fr, jp
  description: 'Welcome to my portfolio' // e.g: Welcome to my website
};

// HERO DATA
export const heroData = {
  title: '',
  name: '',
  subtitle: '',
  cta: '',
};

// ABOUT DATA
export const aboutData = {
  img: 'profile.jpg',
  paragraphOne: 'I am a self-taught web developer from London. I am currently learning full stack web development through The Odin Project',
  paragraphTwo: 'I am passionate about programming and developing my understanding of web development. I have a strong understanding of HTML, CSS and JavaScript fundamentals and I am presently learning my first framework in React',
  paragraphThree: 'I am currently looking for opportunities in front end development. If you wish to know more about me please do not hesitate to ask.',
  resume: 'https://www.resumemaker.online/es.php', // if no resume, the button will not show up
};

// PROJECTS DATA
export const projectsData = [
  {
    id: nanoid(),
    img: 'cv-app.png',
    title: 'React CV Generator',
    info: 'CV Generator app built with class components. Users are able to add in their personal information, they can add in education and work history entries which can be edited and deleted.',
    info2: 'Technologies used: React, JavaScript, CSS',
    url: 'https://sultanp91.github.io/cv-project/',
    repo: 'https://github.com/sultanp91/cv-project', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'memory.jpg',
    title: 'Memory Card',
    info: 'Memory card game built with React functional components making use of useState and useEffect hooks to enable game logic. Try to click all 24 images without clicking on an image twice!',
    info2: 'Technologies used: React, JavaScript, CSS',
    url: 'https://sultanp91.github.io/memory-card/',
    repo: 'https://github.com/sultanp91/memory-card', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'to-do-list.png',
    title: 'To Do List',
    info: 'To Do List made with vanilla JavaScript. Users are are able to create projects and then create tasks within them. Tasks can be edited and deleted. Users are able to find tasks due on that date and also sort through tasks by priority. Dates are formatted using the date-fns package.',
    info2: 'Technologies used: JavaScript, HTML, SASS, WebPack',
    url: 'https://sultanp91.github.io/to-do-list/',
    repo: 'https://github.com/sultanp91/to-do-list', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'weather-app.png',
    title: 'Weather App',
    info: `Weather App which uses the OpenWeather API to retrieve weather data. Users are also able to retrieve weather data by using their current location using the browser's GeoLocation API, which I then converted to a valid location input through the Location IQ API which is then fed back to the OpenWeather API.` ,
    info2: 'Technologies used: HTML, JavaScript, SASS',
    url: 'https://sultanp91.github.io/weather-app/',
    repo: 'https://github.com/sultanp91/weather-app', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'restaurant-page.jpg',
    title: 'Restaurant Page',
    info: 'Landing page for a restaurant. All page content is dynamically generated by JavaScript.',
    info2: 'Technologies used: HTML, CSS, JavaScript',
    url: 'https://sultanp91.github.io/restaurant-page/',
    repo: 'https://github.com/sultanp91/restaurant-page', // if no repo, the button will not show up
  },
];

// CONTACT DATA
export const contactData = {
  cta: '',
  btn: '',
  email: 'sultanp@gmail.com',
};

// FOOTER DATA
export const footerData = {
  networks: [
    {
      id: nanoid(),
      name: 'linkedin',
      url: 'https://www.linkedin.com/in/sultan-alom-parbes-797051159/',
    },
    {
      id: nanoid(),
      name: 'github',
      url: 'https://github.com/sultanp91',
    },
  ],
};

// Github start/fork buttons
export const githubButtons = {
  isEnabled: false, // set to false to disable the GitHub stars/fork buttons
};
